"use client";

import "./globals.css";
import Footer from "./Components/Footer";
import { useState } from "react";
import TopNavbar from "./Components/TopNavbar";
import SideNavbar from "./Components/SideNavbar";
import useMediaQuery from "./utils/useMediaQueries";
import Nav from "./Components/Nav.js";
export const metadata = {
  title: "Rene",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  console.log(sidebarOpen);
  const breakPoint = useMediaQuery(768);
  return (
    <html lang="en">
      <body
        className={`relative ${
          sidebarOpen ? "overflow-y-hidden" : "overflow-y-scroll"
        }`}
      >
        {/* <SideNavbar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} /> */}

        <Nav sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
        <main className="bg-backgroundColor p-10 relative flex min-h-screen h-4/5 flex-col items-center justify-between">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
