import "./globals.css";
import Nav from "./Components/nav";
import Footer from "./Components/Footer";

export const metadata = {
  title: "Rene",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-backgroundColor p-10">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
