import "./globals.css";
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";

export const metadata = {
  title: "Rene",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Nav
          position="relative"
          top="0"
          breakpoint="tablet"
          breakpointValue="flex"
          display="hidden"
        />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
